### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by maxscheurer** [maxscheurer/orcavmd#1]
Quick overview of tasks:

- [x] Basic connection to VMD
- [x] Loading output file
- [x] Checking for version and file type
- [x] Loading Structure
- [x] Loading Coordinate
- [x] Parsing GTO basis (memory issue while assigning the shells to data)
- [x] Parsing basis for semiempirical methods
- [x] Parsing MOs (Only working for s/p shells)
- [x] Workaround for higher ang. mom. shells (g and higher)
  - normalization
- [x] Loading Frames
- [x] More Jobtypes (e.g. Optimization)

... more to come ...

**Comment by maxscheurer** [comment]
Quick overview of tasks:

- [x] Basic connection to VMD
- [x] Loading output file
- [x] Checking for version and file type
- [x] Loading Structure
- [x] Loading Coordinates
- [ ] Parsing STO fit for basis
- [ ] Parsing MOs
- [ ] Loading Frames from QM/MM (i.e. multiple engrad jobs, check for "QMMM" keyword in input)




STO fit:
- obtain from Orca for supported atoms in PM3?
- write python script to parse output from Orca files
- write python script to generate C/C++ code that makes basis set data structures
